services:
  - type: web
    name: ecommerce-backend-prod
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
      - key: UI__Url
        value: "http://localhost:5173" # Update this to your deployed production UI URL
      - key: MongoDbSettings__ConnectionString
        value: "mongodb+srv://anujkumarr97:Anuj54321@ecommercedb.wzm9gjx.mongodb.net/?retryWrites=true&w=majority&appName=ecommercedb"
      - key: MongoDbSettings__DatabaseName
        value: "new_program"
      - key: Jwt__Key
        value: "ThisIsASecretKeyForJwtToken12345"
      - key: Jwt__Issuer
        value: "EcommerceApp"
      - key: Jwt__Audience
        value: "EcommerceUsers"
